name: Cerrar Issue

on:
  pull_request:
    types: [closed]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true #Asegura que el PR ha sido aceptado (merged)
    steps:
      - name: Cerrar Issue
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = github.context.payload.pull_request.number;
            github.issues.update({
              owner: 'MaxLyonel',
              repo: 'TestGitHubActions',
              issue_number: issue_number,
              state: 'closed'
            });
